"""Deterministic financial insight generation from validated FOS outputs."""

from __future__ import annotations

from dataclasses import dataclass
from decimal import Decimal

from src.extract import HistoricalExtractionResult
from src.kpi import AnnualKPI, CurrentSnapshot
from src.transform import CategoryRegistry

ZERO = Decimal("0")
ONE = Decimal("1")


@dataclass(frozen=True, slots=True)
class SpendingEvolution:
    """Latest-year movement for one cash-flow or spending metric."""

    metric_id: str
    metric: str
    metric_group: str
    latest_year: int
    latest_value: Decimal
    prior_year: int | None
    prior_value: Decimal | None
    benchmark_years: tuple[int, ...]
    benchmark_average: Decimal | None
    change_vs_prior_amount: Decimal | None
    change_vs_prior_ratio: Decimal | None
    change_vs_benchmark_amount: Decimal | None
    change_vs_benchmark_ratio: Decimal | None
    direction: str
    signal: str


@dataclass(frozen=True, slots=True)
class FinancialInsight:
    """One evidence-backed observation generated by the insight engine."""

    rank: int
    priority: str
    theme: str
    headline: str
    evidence: str
    implication: str
    recommended_action: str


@dataclass(frozen=True, slots=True)
class ActionItem:
    """One measurable action for the operating plan."""

    rank: int
    priority: str
    area: str
    action: str
    rationale: str
    current_value: Decimal | None
    target_value: Decimal | None
    gap: Decimal | None
    unit: str
    measurement: str
    status: str


@dataclass(frozen=True, slots=True)
class InsightReport:
    """Complete v1.0.0 insight package."""

    latest_year: int
    prior_year: int | None
    benchmark_years: tuple[int, ...]
    monthly_core_spending: Decimal
    emergency_target_months: Decimal
    emergency_target_amount: Decimal
    emergency_fund_gap: Decimal
    fixed_cost_watch_ratio: Decimal
    wealth_building_floor: Decimal
    spending_evolution: tuple[SpendingEvolution, ...]
    insights: tuple[FinancialInsight, ...]
    actions: tuple[ActionItem, ...]


class InsightsEngine:
    """Generate a concise, reproducible financial decision layer.

    Thresholds are internal FOS operating rules. They are deliberately simple,
    documented in the workbook, and should not be interpreted as industry
    standards or individualized investment advice.
    """

    BENCHMARK_YEARS = 3
    EMERGENCY_TARGET_MONTHS = Decimal("3")
    FIXED_COST_WATCH_RATIO = Decimal("0.30")
    WEALTH_BUILDING_FLOOR = Decimal("0.10")
    FLAT_TOLERANCE = Decimal("0.01")

    METRICS = (
        ("income", "True Income", "Cash Flow", "true_income", False),
        (
            "known_expenses",
            "Known Operating Expenses",
            "Cash Flow",
            "known_operating_expenses",
            True,
        ),
        ("fixed_expenses", "Fixed Expenses", "Cash Flow", "fixed_expenses", True),
        (
            "variable_expenses",
            "Variable / Irregular Expenses",
            "Cash Flow",
            "variable_irregular_expenses",
            True,
        ),
        (
            "wealth_building",
            "Wealth Building",
            "Wealth",
            "wealth_building",
            False,
        ),
    )

    CATEGORY_METRICS = (
        "Housing",
        "Transportation",
        "Food",
        "Health",
        "Lifestyle",
        "Household",
        "Family",
        "Pets",
        "Personal",
        "Financial",
        "Capital",
        "Other",
    )

    def __init__(self, category_registry: CategoryRegistry) -> None:
        self.registry = category_registry
        self.entries = {
            str(entry["category_id"]): entry for entry in category_registry.entries()
        }

    @staticmethod
    def _ratio(numerator: Decimal, denominator: Decimal) -> Decimal | None:
        if denominator == 0:
            return None
        return numerator / denominator

    @staticmethod
    def _average(values: list[Decimal]) -> Decimal | None:
        if not values:
            return None
        return sum(values, ZERO) / Decimal(len(values))

    @staticmethod
    def _fmt_currency(value: Decimal) -> str:
        return f"${value:,.0f}"

    @staticmethod
    def _fmt_percent(value: Decimal) -> str:
        return f"{value * Decimal('100'):.1f}%"

    def analyze(
        self,
        extraction: HistoricalExtractionResult,
        annual_kpis: tuple[AnnualKPI, ...],
        current_snapshot: CurrentSnapshot,
    ) -> InsightReport:
        eligible = sorted(
            (item for item in annual_kpis if item.comparison_eligible),
            key=lambda item: item.year,
        )
        complete = sorted(
            (item for item in annual_kpis if item.coverage_status == "Complete"),
            key=lambda item: item.year,
        )
        candidates = eligible or complete or sorted(annual_kpis, key=lambda item: item.year)
        if not candidates:
            raise ValueError("No annual KPI history is available for insight generation.")

        latest = candidates[-1]
        prior_candidates = [item for item in candidates if item.year < latest.year]
        prior = prior_candidates[-1] if prior_candidates else None
        benchmark_items = tuple(prior_candidates[-self.BENCHMARK_YEARS :])
        benchmark_years = tuple(item.year for item in benchmark_items)

        category_by_year = self._category_spending_by_year(extraction)
        evolution: list[SpendingEvolution] = []
        for metric_id, metric, group, attribute, is_expense in self.METRICS:
            values = {item.year: getattr(item, attribute) for item in candidates}
            evolution.append(
                self._build_evolution(
                    metric_id=metric_id,
                    metric=metric,
                    metric_group=group,
                    latest=latest,
                    prior=prior,
                    benchmark_items=benchmark_items,
                    values_by_year=values,
                    is_expense=is_expense,
                )
            )

        for category in self.CATEGORY_METRICS:
            values = {
                item.year: category_by_year.get(item.year, {}).get(category, ZERO)
                for item in candidates
            }
            comparison_years = {latest.year, *(item.year for item in benchmark_items)}
            if prior is not None:
                comparison_years.add(prior.year)
            if not any(values.get(year, ZERO) for year in comparison_years):
                continue
            evolution.append(
                self._build_evolution(
                    metric_id=f"category_{category.casefold().replace(' ', '_')}",
                    metric=category,
                    metric_group="Spending Category",
                    latest=latest,
                    prior=prior,
                    benchmark_items=benchmark_items,
                    values_by_year=values,
                    is_expense=True,
                )
            )

        monthly_core = latest.core_spending / Decimal("12") if latest.core_spending else ZERO
        emergency_target = monthly_core * self.EMERGENCY_TARGET_MONTHS
        emergency_gap = max(ZERO, emergency_target - current_snapshot.savings_cash)

        insights = self._build_insights(
            latest=latest,
            prior=prior,
            current_snapshot=current_snapshot,
            evolution=evolution,
            emergency_target=emergency_target,
            emergency_gap=emergency_gap,
        )
        actions = self._build_actions(
            latest=latest,
            prior=prior,
            current_snapshot=current_snapshot,
            evolution=evolution,
            emergency_target=emergency_target,
            emergency_gap=emergency_gap,
        )

        return InsightReport(
            latest_year=latest.year,
            prior_year=prior.year if prior else None,
            benchmark_years=benchmark_years,
            monthly_core_spending=monthly_core,
            emergency_target_months=self.EMERGENCY_TARGET_MONTHS,
            emergency_target_amount=emergency_target,
            emergency_fund_gap=emergency_gap,
            fixed_cost_watch_ratio=self.FIXED_COST_WATCH_RATIO,
            wealth_building_floor=self.WEALTH_BUILDING_FLOOR,
            spending_evolution=tuple(evolution),
            insights=tuple(insights),
            actions=tuple(actions),
        )

    def _category_spending_by_year(
        self, extraction: HistoricalExtractionResult
    ) -> dict[int, dict[str, Decimal]]:
        result: dict[int, dict[str, Decimal]] = {}
        for sheet in extraction.sheets:
            year_values: dict[str, Decimal] = {}
            transactions = (
                list(sheet.result.transfers)
                + list(sheet.result.variable_expenses)
                + list(sheet.result.fixed_expenses)
            )
            for transaction in transactions:
                entry = self.entries[transaction.category_id]
                if entry["category_type"] == "Transfer":
                    continue
                master = str(entry["master_category"])
                year_values[master] = year_values.get(master, ZERO) + transaction.amount
            result[sheet.year] = year_values
        return result

    def _build_evolution(
        self,
        *,
        metric_id: str,
        metric: str,
        metric_group: str,
        latest: AnnualKPI,
        prior: AnnualKPI | None,
        benchmark_items: tuple[AnnualKPI, ...],
        values_by_year: dict[int, Decimal],
        is_expense: bool,
    ) -> SpendingEvolution:
        latest_value = values_by_year.get(latest.year, ZERO)
        prior_value = values_by_year.get(prior.year, ZERO) if prior else None
        benchmark_values = [values_by_year.get(item.year, ZERO) for item in benchmark_items]
        benchmark_average = self._average(benchmark_values)
        change_prior = latest_value - prior_value if prior_value is not None else None
        ratio_prior = (
            self._ratio(change_prior, prior_value)
            if change_prior is not None and prior_value is not None
            else None
        )
        change_benchmark = (
            latest_value - benchmark_average if benchmark_average is not None else None
        )
        ratio_benchmark = (
            self._ratio(change_benchmark, benchmark_average)
            if change_benchmark is not None and benchmark_average is not None
            else None
        )

        if ratio_prior is None:
            direction = "No comparison"
            signal = "Context"
        elif abs(ratio_prior) <= self.FLAT_TOLERANCE:
            direction = "Stable"
            signal = "Stable"
        elif ratio_prior > 0:
            direction = "Increase"
            signal = "Watch" if is_expense else "Favourable"
        else:
            direction = "Decrease"
            signal = "Favourable" if is_expense else "Watch"

        return SpendingEvolution(
            metric_id=metric_id,
            metric=metric,
            metric_group=metric_group,
            latest_year=latest.year,
            latest_value=latest_value,
            prior_year=prior.year if prior else None,
            prior_value=prior_value,
            benchmark_years=tuple(item.year for item in benchmark_items),
            benchmark_average=benchmark_average,
            change_vs_prior_amount=change_prior,
            change_vs_prior_ratio=ratio_prior,
            change_vs_benchmark_amount=change_benchmark,
            change_vs_benchmark_ratio=ratio_benchmark,
            direction=direction,
            signal=signal,
        )

    def _evolution_by_id(
        self, evolution: list[SpendingEvolution]
    ) -> dict[str, SpendingEvolution]:
        return {item.metric_id: item for item in evolution}

    def _largest_category_increases(
        self, evolution: list[SpendingEvolution], count: int = 2
    ) -> list[SpendingEvolution]:
        increases = [
            item
            for item in evolution
            if item.metric_group == "Spending Category"
            and item.change_vs_prior_amount is not None
            and item.change_vs_prior_amount > 0
        ]
        return sorted(
            increases,
            key=lambda item: item.change_vs_prior_amount or ZERO,
            reverse=True,
        )[:count]

    def _build_insights(
        self,
        *,
        latest: AnnualKPI,
        prior: AnnualKPI | None,
        current_snapshot: CurrentSnapshot,
        evolution: list[SpendingEvolution],
        emergency_target: Decimal,
        emergency_gap: Decimal,
    ) -> list[FinancialInsight]:
        by_id = self._evolution_by_id(evolution)
        results: list[FinancialInsight] = []

        emergency_months = current_snapshot.emergency_fund_months or ZERO
        results.append(
            FinancialInsight(
                rank=1,
                priority="High" if emergency_months < Decimal("1.5") else "Medium",
                theme="Liquidity",
                headline="Liquid reserves are the clearest resilience gap.",
                evidence=(
                    f"Savings cover {emergency_months:.1f} months of core spending. "
                    f"The FOS 3-month operating target is {self._fmt_currency(emergency_target)}, "
                    f"leaving a gap of {self._fmt_currency(emergency_gap)}."
                ),
                implication=(
                    "Strong home equity and net worth do not provide the same day-to-day "
                    "protection as accessible cash."
                ),
                recommended_action=(
                    "Protect the current cash floor and build toward three months of core spending."
                ),
            )
        )

        loc_ratio = current_snapshot.unsecured_debt_ratio or ZERO
        results.append(
            FinancialInsight(
                rank=2,
                priority="High" if current_snapshot.line_of_credit_balance > 0 else "Low",
                theme="Debt",
                headline="The line of credit remains the most actionable debt pressure.",
                evidence=(
                    f"Current LOC balance is {self._fmt_currency(current_snapshot.line_of_credit_balance)}, "
                    f"equal to {self._fmt_percent(loc_ratio)} of {latest.year} true income."
                ),
                implication=(
                    "Reducing unsecured debt improves cash-flow resilience without disturbing "
                    "the long-term mortgage or low-rate vehicle schedule."
                ),
                recommended_action="Direct available debt-reduction capacity to the LOC until it reaches zero.",
            )
        )

        fixed = by_id["fixed_expenses"]
        income = by_id["income"]
        fixed_change_pp = ZERO
        if prior and latest.fixed_cost_ratio is not None and prior.fixed_cost_ratio is not None:
            fixed_change_pp = latest.fixed_cost_ratio - prior.fixed_cost_ratio
        results.append(
            FinancialInsight(
                rank=3,
                priority=(
                    "High"
                    if (latest.fixed_cost_ratio or ZERO) >= self.FIXED_COST_WATCH_RATIO
                    else "Medium"
                ),
                theme="Cash Flow",
                headline="Fixed-cost pressure rose while income moved lower.",
                evidence=(
                    f"Fixed expenses were {self._fmt_percent(latest.fixed_cost_ratio or ZERO)} of income, "
                    f"up {fixed_change_pp * Decimal('100'):.1f} percentage points from "
                    f"{prior.year if prior else 'the prior comparison'}. "
                    f"Income changed {self._fmt_percent(income.change_vs_prior_ratio or ZERO)} year over year."
                ),
                implication=(
                    "A larger committed-cost share leaves less room for irregular costs even when "
                    "total known spending is stable."
                ),
                recommended_action=(
                    "Hold new recurring commitments and review renewals before the fixed-cost ratio reaches 30%."
                ),
            )
        )

        wealth_rate = latest.wealth_building_rate or ZERO
        results.append(
            FinancialInsight(
                rank=4,
                priority="Protect" if wealth_rate >= self.WEALTH_BUILDING_FLOOR else "High",
                theme="Wealth",
                headline=(
                    "Wealth building remains a financial strength."
                    if wealth_rate >= self.WEALTH_BUILDING_FLOOR
                    else "Wealth building has fallen below the FOS operating floor."
                ),
                evidence=(
                    f"{self._fmt_currency(latest.wealth_building)} was directed to wealth building in "
                    f"{latest.year}, equal to {self._fmt_percent(wealth_rate)} of true income."
                ),
                implication=(
                    "Maintaining this rate supports retirement and education goals while other pressures are addressed."
                ),
                recommended_action=(
                    "Protect a minimum 10% wealth-building rate unless short-term liquidity requires a temporary adjustment."
                ),
            )
        )

        top_increases = self._largest_category_increases(evolution)
        if top_increases:
            combined = sum(
                (item.change_vs_prior_amount or ZERO for item in top_increases), ZERO
            )
            labels = " and ".join(item.metric for item in top_increases)
            evidence_parts = [
                f"{item.metric} {self._fmt_currency(item.change_vs_prior_amount or ZERO)}"
                for item in top_increases
            ]
            results.append(
                FinancialInsight(
                    rank=5,
                    priority="Medium",
                    theme="Spending",
                    headline=f"{labels} produced the largest mapped spending increases.",
                    evidence=(
                        ", ".join(evidence_parts)
                        + f"; combined increase {self._fmt_currency(combined)} versus {prior.year if prior else 'the prior year'}."
                    ),
                    implication=(
                        "The increases may be necessary, but they are the best starting point for a transaction-level review."
                    ),
                    recommended_action=(
                        "Review these categories for recurring changes, one-time items, and avoidable leakage before setting a reduction target."
                    ),
                )
            )

        results.append(
            FinancialInsight(
                rank=6,
                priority="Low" if (latest.data_coverage_ratio or ZERO) >= Decimal("0.95") else "Medium",
                theme="Data Quality",
                headline="Classification coverage is usable but not complete.",
                evidence=(
                    f"{self._fmt_percent(latest.data_coverage_ratio or ZERO)} of recorded outflows were classified; "
                    f"{self._fmt_currency(latest.unknown_amount)} remains unmapped in {latest.year}."
                ),
                implication=(
                    "The dashboard is decision-useful, but category conclusions should retain a small uncertainty allowance."
                ),
                recommended_action="Map the largest current-year exception labels before the next planning review.",
            )
        )
        return results

    def _build_actions(
        self,
        *,
        latest: AnnualKPI,
        prior: AnnualKPI | None,
        current_snapshot: CurrentSnapshot,
        evolution: list[SpendingEvolution],
        emergency_target: Decimal,
        emergency_gap: Decimal,
    ) -> list[ActionItem]:
        fixed_ratio = latest.fixed_cost_ratio or ZERO
        fixed_target_amount = latest.true_income * self.FIXED_COST_WATCH_RATIO
        fixed_headroom = max(ZERO, fixed_target_amount - latest.fixed_expenses)
        wealth_target = latest.true_income * self.WEALTH_BUILDING_FLOOR
        wealth_buffer = latest.wealth_building - wealth_target
        top_increases = self._largest_category_increases(evolution)
        focus_current = sum((item.latest_value for item in top_increases), ZERO)
        focus_prior = sum((item.prior_value or ZERO for item in top_increases), ZERO)

        return [
            ActionItem(
                rank=1,
                priority="High",
                area="Debt",
                action="Reduce the line of credit to zero.",
                rationale="It is the largest immediately actionable unsecured balance.",
                current_value=current_snapshot.line_of_credit_balance,
                target_value=ZERO,
                gap=current_snapshot.line_of_credit_balance,
                unit="$",
                measurement="LOC balance from A & L",
                status="In progress" if current_snapshot.line_of_credit_balance > 0 else "Complete",
            ),
            ActionItem(
                rank=2,
                priority="High",
                area="Liquidity",
                action="Build a three-month core-spending reserve.",
                rationale="Current accessible savings cover less than one month of core spending.",
                current_value=current_snapshot.savings_cash,
                target_value=emergency_target,
                gap=emergency_gap,
                unit="$",
                measurement="Savings balance ÷ monthly core spending",
                status="In progress" if emergency_gap > 0 else "Complete",
            ),
            ActionItem(
                rank=3,
                priority="Protect",
                area="Wealth",
                action="Maintain at least a 10% wealth-building rate.",
                rationale="The current rate is a financial strength and supports long-term goals.",
                current_value=latest.wealth_building,
                target_value=wealth_target,
                gap=wealth_buffer,
                unit="$ / year",
                measurement="Wealth-building transfers ÷ true income",
                status="On track" if wealth_buffer >= 0 else "Needs action",
            ),
            ActionItem(
                rank=4,
                priority="Medium",
                area="Fixed Costs",
                action="Keep fixed expenses below 30% of true income.",
                rationale="The ratio increased materially in the latest complete year.",
                current_value=latest.fixed_expenses,
                target_value=fixed_target_amount,
                gap=fixed_headroom,
                unit="$ / year",
                measurement="Fixed expenses ÷ true income",
                status="Monitor" if fixed_ratio < self.FIXED_COST_WATCH_RATIO else "Needs action",
            ),
            ActionItem(
                rank=5,
                priority="Medium",
                area="Spending Review",
                action=(
                    "Review " + " and ".join(item.metric for item in top_increases)
                    if top_increases
                    else "Review the largest mapped spending increases"
                ),
                rationale="These categories created the largest year-over-year increases.",
                current_value=focus_current if top_increases else None,
                target_value=None,
                gap=(focus_current - focus_prior) if top_increases else None,
                unit="$ / year",
                measurement="Category totals in Spending_Evolution",
                status="Review",
            ),
            ActionItem(
                rank=6,
                priority="Low",
                area="Data Quality",
                action="Map the largest current-year exception labels.",
                rationale="Better classification improves category-level decisions without changing source totals.",
                current_value=latest.unknown_amount,
                target_value=ZERO,
                gap=latest.unknown_amount,
                unit="$",
                measurement="Exceptions and DataCoverageRatio",
                status="Review",
            ),
        ]
